---
# CI Workflow - Tests and Linting
#
# Runs on all pull requests to develop and main branches
# Validates code quality before merge

name: CI

"on":
  pull_request:
    branches:
      - develop
      - main

concurrency:
  group: ci-${{ gitea.ref }}
  cancel-in-progress: true

jobs:
  # Dashboard (Next.js) checks
  dashboard-lint:
    name: Dashboard Lint & Type Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dashboard

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Run TypeScript check
        run: npx tsc --noEmit

  dashboard-test:
    name: Dashboard Tests
    runs-on: ubuntu-latest
    needs: dashboard-lint
    defaults:
      run:
        working-directory: dashboard

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  dashboard-build:
    name: Dashboard Build Check
    runs-on: ubuntu-latest
    needs: dashboard-lint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          cd dashboard
          docker build -t wab-dashboard:test .

  # WordPress Plugin (PHP) checks
  plugin-lint:
    name: Plugin Lint (PHPCS)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          tools: composer

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      - name: Run PHPCS
        run: composer phpcs || true
        continue-on-error: true

  plugin-test:
    name: Plugin Tests (PHPUnit)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          tools: composer
          coverage: xdebug

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      - name: Run PHPUnit
        run: composer test

  # Summary job for branch protection
  ci-success:
    name: CI Success
    runs-on: ubuntu-latest
    needs:
      - dashboard-lint
      - dashboard-test
      - dashboard-build
      - plugin-lint
      - plugin-test
    if: always()

    steps:
      - name: Check all jobs passed
        run: |
          if [[ "${{ needs.dashboard-lint.result }}" == "failure" ]]; then
            echo "Dashboard lint failed"
            exit 1
          fi
          if [[ "${{ needs.dashboard-test.result }}" == "failure" ]]; then
            echo "Dashboard tests failed"
            exit 1
          fi
          if [[ "${{ needs.dashboard-build.result }}" == "failure" ]]; then
            echo "Dashboard build failed"
            exit 1
          fi
          if [[ "${{ needs.plugin-test.result }}" == "failure" ]]; then
            echo "Plugin tests failed"
            exit 1
          fi
          echo "All required checks passed"
