---
# Deploy to Staging
#
# Automatically deploys to staging environment on push to develop branch
# - Dashboard: Docker image to staging server
# - WordPress Plugin: rsync to UruShop staging server
#
# Since Gitea is on the local network, no VPN is needed

name: Deploy Staging

"on":
  push:
    branches:
      - develop
  workflow_dispatch:

env:
  REGISTRY: gitea.internal.uru.onl
  IMAGE_NAME: Renzo/attribution-bridge/dashboard

concurrency:
  group: deploy-staging
  cancel-in-progress: false

jobs:
  build-dashboard:
    name: Build Dashboard Image
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.meta.outputs.tags }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Gitea Container Registry
        run: |
          echo "${{ secrets.REGISTRY_TOKEN }}" | \
            docker login ${{ env.REGISTRY }} \
            -u ${{ gitea.actor }} --password-stdin

      - name: Build and tag image
        run: |
          cd dashboard
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:develop .
          docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:develop \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:develop-${{ gitea.sha }}

      - name: Push image
        run: |
          IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          docker push ${IMAGE}:develop
          docker push ${IMAGE}:develop-${{ gitea.sha }}

  deploy-dashboard:
    name: Deploy Dashboard to Staging
    runs-on: ubuntu-latest
    needs: build-dashboard

    steps:
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DASHBOARD_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.DASHBOARD_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to staging server
        env:
          HOST: ${{ secrets.DASHBOARD_HOST }}
          REGISTRY: ${{ env.REGISTRY }}
          IMAGE: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:develop
        run: |
          ssh root@$HOST << 'DEPLOY'
            set -e
            cd /opt/wab

            # Login to Gitea registry
            echo "${{ secrets.REGISTRY_TOKEN }}" | \
              docker login ${{ env.REGISTRY }} \
              -u ${{ gitea.actor }} --password-stdin

            # Pull latest image
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:develop

            # Restart staging stack
            docker compose -p wab-staging -f docker-compose.staging.yml pull
            docker compose -p wab-staging -f docker-compose.staging.yml up -d

            # Show status
            docker compose -p wab-staging -f docker-compose.staging.yml ps

            # Cleanup old images
            docker image prune -f
          DEPLOY

      - name: Run database migrations
        timeout-minutes: 3
        env:
          HOST: ${{ secrets.DASHBOARD_HOST }}
        run: |
          echo "Running database migrations..."
          ssh -o ConnectTimeout=30 -o BatchMode=yes root@$HOST \
            "docker exec wab-staging-dashboard npx tsx src/db/migrate.ts"
          echo "Migrations completed"

      - name: Verify deployment
        env:
          HOST: ${{ secrets.DASHBOARD_HOST }}
        run: |
          sleep 5
          curl -sf http://$HOST:3001/api/health || exit 1
          echo "Dashboard staging deployment verified"

  deploy-plugin:
    name: Deploy Plugin to Staging
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Backup current plugin
        id: backup
        timeout-minutes: 2
        env:
          HOST: ${{ secrets.SSH_HOST }}
          WP_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |
          PLUGIN_PATH="${WP_PATH}/wp-content/plugins/woo-attribution-bridge"
          BACKUP_PATH="${WP_PATH}/wp-content/plugins/.wab-backup-staging"

          # Create backup of current plugin (if exists)
          ssh root@${HOST} << BACKUP
            if [ -d "${PLUGIN_PATH}" ]; then
              rm -rf ${BACKUP_PATH}
              cp -r ${PLUGIN_PATH} ${BACKUP_PATH}
              echo "Backup created at ${BACKUP_PATH}"
            else
              echo "No existing plugin to backup"
            fi
          BACKUP

          echo "backup_path=${BACKUP_PATH}" >> $GITHUB_OUTPUT

      - name: Deploy plugin via rsync
        timeout-minutes: 5
        env:
          HOST: ${{ secrets.SSH_HOST }}
          WP_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |
          PLUGIN_PATH="${WP_PATH}/wp-content/plugins/woo-attribution-bridge"

          # Ensure plugin directory exists
          ssh root@${HOST} "mkdir -p ${PLUGIN_PATH}"

          # Rsync plugin files
          rsync -avz --delete --timeout=120 \
            --exclude '.git' \
            --exclude 'tests' \
            --exclude 'composer.json' \
            --exclude 'composer.lock' \
            --exclude 'phpunit.xml' \
            --exclude 'phpcs.xml' \
            --exclude '.phpcs.xml' \
            ./src/ \
            root@${HOST}:${PLUGIN_PATH}/

          # Fix permissions (CloudPanel uses clp:clp for web files)
          ssh root@${HOST} "chown -R clp:clp ${PLUGIN_PATH}"
          ssh root@${HOST} "chmod -R u=rwX,go=rX ${PLUGIN_PATH}"

          echo "Plugin deployed to staging with correct permissions"

      - name: Verify WordPress site health
        id: health_check
        timeout-minutes: 2
        env:
          HOST: ${{ secrets.SSH_HOST }}
          SITE_URL: ${{ secrets.SITE_URL }}
        run: |
          # Skip if SITE_URL not configured
          if [ -z "${SITE_URL}" ]; then
            echo "::warning::SITE_URL not set, skipping health check"
            exit 0
          fi

          echo "Waiting for WordPress to reload..."
          sleep 5

          # Check if site returns 200 (not 500 critical error)
          HTTP_CODE=$(ssh root@${HOST} \
            "curl -sL -o /dev/null -w '%{http_code}' --max-time 30 ${SITE_URL}")

          echo "HTTP response code: ${HTTP_CODE}"

          if [ "$HTTP_CODE" -ge 500 ]; then
            echo "CRITICAL: Site returning HTTP ${HTTP_CODE}"
            exit 1
          elif [ "$HTTP_CODE" -ge 400 ]; then
            echo "WARNING: HTTP ${HTTP_CODE} (may be auth required)"
          else
            echo "Site healthy with HTTP ${HTTP_CODE}"
          fi

      - name: Rollback on failure
        if: failure()
        timeout-minutes: 2
        env:
          HOST: ${{ secrets.SSH_HOST }}
          WP_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |
          PLUGIN_PATH="${WP_PATH}/wp-content/plugins/woo-attribution-bridge"
          BACKUP_PATH="${WP_PATH}/wp-content/plugins/.wab-backup-staging"

          echo "Health check failed! Rolling back..."

          ssh root@${HOST} << ROLLBACK
            if [ -d "${BACKUP_PATH}" ]; then
              rm -rf ${PLUGIN_PATH}
              mv ${BACKUP_PATH} ${PLUGIN_PATH}
              echo "Rollback complete - restored previous version"
            else
              echo "No backup found - cannot rollback"
              exit 1
            fi
          ROLLBACK

  notify-success:
    name: Notify Success
    runs-on: ubuntu-latest
    needs:
      - deploy-dashboard
      - deploy-plugin
    if: success()

    steps:
      - name: Deployment summary
        run: |
          echo "## Staging Deployment Complete"
          echo ""
          echo "- Dashboard: Deployed to staging"
          echo "- WordPress Plugin: Deployed to staging site"
          echo ""
          echo "Commit: ${{ gitea.sha }}"
